### Register (optional)
# POST http://localhost:8080/auth/register
# Content-Type: application/json
#
# {
#   "username": "markus",
#   "password": "test123"
# }

### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "markus",
  "password": "test123"
}

### Create / Update Emission
POST http://localhost:8080/emissions
Content-Type: application/json

{
  "country": "Austria",
  "year": 2023,
  "co2Emission": 12345.67,
  "username": "markus"
}

### Get Emission
GET http://localhost:8080/emissions/Austria