spring.application.name=co2app
spring.datasource.url=jdbc:mysql://localhost:3306/co2-mysql
spring.datasource.username=co2user
spring.datasource.password=co2pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect